import type { Recipe } from '../database/repository'

// Email service placeholder
// In production, integrate with SendGrid, Nodemailer, or another email service

interface EmailConfig {
  service: 'sendgrid' | 'smtp' | 'none'
  apiKey?: string
  smtpHost?: string
  smtpPort?: number
  smtpUser?: string
  smtpPass?: string
  fromEmail: string
  fromName: string
}

// Load config from environment variables
function getEmailConfig(): EmailConfig {
  const service = (process.env.EMAIL_SERVICE?.toLowerCase() || 'none') as EmailConfig['service']
  return {
    service: ['sendgrid', 'smtp', 'none'].includes(service) ? service : 'none',
    apiKey: process.env.SENDGRID_API_KEY,
    smtpHost: process.env.SMTP_HOST,
    smtpPort: process.env.SMTP_PORT ? parseInt(process.env.SMTP_PORT) : undefined,
    smtpUser: process.env.SMTP_USER,
    smtpPass: process.env.SMTP_PASS,
    fromEmail: process.env.SMTP_FROM_EMAIL || 'recipes@vegucationstation.local',
    fromName: process.env.SMTP_FROM_NAME || 'VegucationStation',
  }
}

export function isEmailEnabled(): boolean {
  const config = getEmailConfig()
  return config.service !== 'none'
}

function formatRecipesAsHtml(recipes: Recipe[]): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; }
    h1 { color: #22c55e; }
    h2 { color: #f97316; border-bottom: 2px solid #f97316; padding-bottom: 5px; }
    .recipe { margin-bottom: 30px; background: #fffbeb; padding: 20px; border-radius: 10px; }
    .meta { color: #666; font-size: 14px; margin-bottom: 15px; }
    .ingredients { background: white; padding: 15px; border-radius: 5px; margin: 10px 0; }
    .ingredients ul { margin: 0; padding-left: 20px; }
    .steps ol { padding-left: 20px; }
    .steps li { margin-bottom: 10px; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #ddd; color: #666; font-size: 12px; }
  </style>
</head>
<body>
  <h1>Your Farmers Market Recipes</h1>
  <p>Here are the recipes you requested from VegucationStation!</p>

  ${recipes
    .map(
      (recipe) => `
    <div class="recipe">
      <h2>${recipe.title}</h2>
      <p>${recipe.description}</p>
      <div class="meta">
        <strong>Prep Time:</strong> ${recipe.prepTime} |
        <strong>Difficulty:</strong> ${recipe.difficulty} |
        <strong>Servings:</strong> ${recipe.servings}
      </div>

      <div class="ingredients">
        <h3>Ingredients</h3>
        <ul>
          ${recipe.ingredients.map((ing) => `<li>${ing}</li>`).join('')}
        </ul>
      </div>

      <div class="steps">
        <h3>Instructions</h3>
        <ol>
          ${recipe.steps.map((step) => `<li>${step}</li>`).join('')}
        </ol>
      </div>
    </div>
  `
    )
    .join('')}

  <div class="footer">
    <p>Recipes generated by VegucationStation - your farmers market education companion.</p>
    <p>Support your local farmers!</p>
  </div>
</body>
</html>
  `
}

function formatRecipesAsText(recipes: Recipe[]): string {
  return recipes
    .map(
      (recipe) => `
========================================
${recipe.title.toUpperCase()}
========================================
${recipe.description}

Prep Time: ${recipe.prepTime}
Difficulty: ${recipe.difficulty}
Servings: ${recipe.servings}

INGREDIENTS:
${recipe.ingredients.map((ing) => `  - ${ing}`).join('\n')}

INSTRUCTIONS:
${recipe.steps.map((step, i) => `  ${i + 1}. ${step}`).join('\n')}
`
    )
    .join('\n\n---\n')
}

export async function sendRecipeEmail(
  toEmail: string,
  recipes: Recipe[]
): Promise<boolean> {
  const emailConfig = getEmailConfig()
  const htmlContent = formatRecipesAsHtml(recipes)
  const textContent = formatRecipesAsText(recipes)

  console.log('Attempting to send email to:', toEmail)
  console.log('Email config service:', emailConfig.service)
  console.log('HTML content length:', htmlContent.length)

  // Check email service configuration
  if (emailConfig.service === 'none') {
    console.log('Email service not configured. Would send:')
    console.log('To:', toEmail)
    console.log('Subject: Your Farmers Market Recipes from VegucationStation')
    console.log('Content:', textContent.substring(0, 500) + '...')

    // In development/demo mode, we'll pretend it succeeded
    // In production, this should return false or throw an error
    return true
  }

  if (emailConfig.service === 'sendgrid') {
    // SendGrid integration
    // Requires: npm install @sendgrid/mail
    // const sgMail = require('@sendgrid/mail')
    // sgMail.setApiKey(emailConfig.apiKey)
    // await sgMail.send({ ... })
    console.log('SendGrid not yet implemented')
    return false
  }

  if (emailConfig.service === 'smtp') {
    // Nodemailer SMTP integration
    // Requires: npm install nodemailer
    // const transporter = nodemailer.createTransport({ ... })
    // await transporter.sendMail({ ... })
    console.log('SMTP not yet implemented')
    return false
  }

  return false
}

// Export for testing
export { formatRecipesAsHtml, formatRecipesAsText }
